### ISSUE TITLE
Use of forget gate from sequence to sequence

### ISSUE THREAD

**Issue by aurotripathy** [sussexwearlab/DeepConvLSTM#2]
Hi:
I have reproduced your results for both training and testing. 

I also appreciate your help with suggesting hyper-parameters for  training.

One question I have is the use of the LSTM forget gate. In other sequence classifier implementations, I see the use a sequence marker to demarcate the start of a sequence. This is yet another input, in addition to the data input and the label input.  The sequence marker is presumably used to erase the LSTM memory across sequences. This may be implicit in your network as it is assumed that all sequences in the batch are of the same length and the erasure is "automatic".

It would be very helpful to have your thoughts.

Thank you

**Comment by sussexwearlab** [comment]
Hi @aurotripathy ,

Indeed the implementation of this network considers each sequence (represented as the second dimension of the input tensor) as independent. Hence, we can interpret that the gates are "erased" for each data sequence. All sequences in the batch do not have to be of the same length, since you can define a mask (mask_input parameter) to define sequences of variable length. 

For the scenario where you want the layer to keep the state of some gates for successive sequences (typically sequence to sequence problems), a possible solution is to extend the LSTMLayer and return the gates of interest as a single tensor, feeding such gates back to the layer at every timestep. You can see a nice implementation from @tencia in https://gist.github.com/tencia/e2e8686228b670bf9002.

Hope it helps
